services:
  neo4j:
    image: neo4j:5.26.0
    container_name: graphiti-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - graphiti-network
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:latest
    container_name: graphiti-mcp-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    env_file:
      - path: .env
        required: true
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - graphiti-network
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  graphiti-network:
    name: graphiti-network
    driver: bridge
